### ISSUE TITLE
Don't use Face Recognition in Production

### ISSUE THREAD

**Issue by Exadra37** [mpociot/laravel-face-auth#2]
Any kind of Face Recognition, using the camera of the device as a form of Authentication is flawed.

You only need to hold a good photo in front of the camera to by pass it.

Using this for authentication is like shooting in your own foot and contributing for a more insecure web.

Please put in the top of your README an alert for this issue.

Thanks

**Comment by mpociot** [comment]
Yeah, wanted to add something like this to the repo too.
Done :)
